# Generated by Django 5.0.4 on 2025-01-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretSanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seed', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSantaRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_santa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='social.secretsanta')),
            ],
        ),
    ]
